//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://training.gov.au/services/", ClrNamespace="training.gov.au.services")]

namespace training.gov.au.services
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RtoClassificationSchemeResult", Namespace="http://training.gov.au/services/")]
    public partial class RtoClassificationSchemeResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool AllowMultipleValuesField;
        
        private training.gov.au.services.ClassificationValue[] ClassificationValuesField;
        
        private string DescriptionField;
        
        private bool IsProtectedField;
        
        private bool IsRequiredField;
        
        private string NameField;
        
        private string SchemeCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowMultipleValues
        {
            get
            {
                return this.AllowMultipleValuesField;
            }
            set
            {
                this.AllowMultipleValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public training.gov.au.services.ClassificationValue[] ClassificationValues
        {
            get
            {
                return this.ClassificationValuesField;
            }
            set
            {
                this.ClassificationValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProtected
        {
            get
            {
                return this.IsProtectedField;
            }
            set
            {
                this.IsProtectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRequired
        {
            get
            {
                return this.IsRequiredField;
            }
            set
            {
                this.IsRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SchemeCode
        {
            get
            {
                return this.SchemeCodeField;
            }
            set
            {
                this.SchemeCodeField = value;
            }
        }
    }
    
    // ClassificationValue is defined in TgaTraining.cs. Duplicate removed here.
    
    // AbstractDto is defined in TgaTraining.cs. Duplicate removed here.
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificationValueUpdateRequest", Namespace="http://training.gov.au/services/")]
    public partial class ClassificationValueUpdateRequest : training.gov.au.services.AbstractDto
    {
        
        private training.gov.au.services.ClassificationValue[] ClassificationValuesField;
        
        private string SchemeCodeField;
        
        private training.gov.au.services.ClassificationTarget TargetField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public training.gov.au.services.ClassificationValue[] ClassificationValues
        {
            get
            {
                return this.ClassificationValuesField;
            }
            set
            {
                this.ClassificationValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SchemeCode
        {
            get
            {
                return this.SchemeCodeField;
            }
            set
            {
                this.SchemeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public training.gov.au.services.ClassificationTarget Target
        {
            get
            {
                return this.TargetField;
            }
            set
            {
                this.TargetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificationScheme", Namespace="http://training.gov.au/services/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(training.gov.au.services.RtoClassificationScheme))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(training.gov.au.services.NrtClassificationScheme))]
    public partial class ClassificationScheme : training.gov.au.services.AbstractDto
    {
        
        private bool AllowMultipleValuesField;
        
        private training.gov.au.services.ClassificationValue[] ClassificationValuesField;
        
        private string DescriptionField;
        
        private bool IsProtectedField;
        
        private string NameField;
        
        private string SchemeCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowMultipleValues
        {
            get
            {
                return this.AllowMultipleValuesField;
            }
            set
            {
                this.AllowMultipleValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public training.gov.au.services.ClassificationValue[] ClassificationValues
        {
            get
            {
                return this.ClassificationValuesField;
            }
            set
            {
                this.ClassificationValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProtected
        {
            get
            {
                return this.IsProtectedField;
            }
            set
            {
                this.IsProtectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SchemeCode
        {
            get
            {
                return this.SchemeCodeField;
            }
            set
            {
                this.SchemeCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RtoClassificationScheme", Namespace="http://training.gov.au/services/")]
    public partial class RtoClassificationScheme : training.gov.au.services.ClassificationScheme
    {
        
        private bool IsRequiredField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRequired
        {
            get
            {
                return this.IsRequiredField;
            }
            set
            {
                this.IsRequiredField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NrtClassificationScheme", Namespace="http://training.gov.au/services/")]
    public partial class NrtClassificationScheme : training.gov.au.services.ClassificationScheme
    {
        
        private training.gov.au.services.TrainingComponentTypes AppliesToComponentTypesField;
        
        private training.gov.au.services.TrainingComponentTypes RequiredForComponentTypesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public training.gov.au.services.TrainingComponentTypes AppliesToComponentTypes
        {
            get
            {
                return this.AppliesToComponentTypesField;
            }
            set
            {
                this.AppliesToComponentTypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public training.gov.au.services.TrainingComponentTypes RequiredForComponentTypes
        {
            get
            {
                return this.RequiredForComponentTypesField;
            }
            set
            {
                this.RequiredForComponentTypesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionOnEntity", Namespace="http://training.gov.au/services/")]
    public enum ActionOnEntity : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificationTarget", Namespace="http://training.gov.au/services/")]
    public enum ClassificationTarget : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rto = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nrt = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrainingComponentTypes", Namespace="http://training.gov.au/services/")]
    public enum TrainingComponentTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccreditedCourse = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Qualification = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unit = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SkillSet = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnitContextualisation = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TrainingPackage = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccreditedCourseModule = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TrainingPackageGroup = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QualsSkillsUnits = 14,
    }
    
    // NrtClassificationSchemeResult is defined in TgaTraining.cs. Duplicate removed here.
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificationGetClassificationRequest", Namespace="http://training.gov.au/services/")]
    public partial class ClassificationGetClassificationRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClassificationSchemeField;
        
        private training.gov.au.services.ClassificationTarget ClassificationTargetField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClassificationScheme
        {
            get
            {
                return this.ClassificationSchemeField;
            }
            set
            {
                this.ClassificationSchemeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public training.gov.au.services.ClassificationTarget ClassificationTarget
        {
            get
            {
                return this.ClassificationTargetField;
            }
            set
            {
                this.ClassificationTargetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificationPurpose", Namespace="http://training.gov.au/services/")]
    public partial class ClassificationPurpose : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private string PurposeCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PurposeCode
        {
            get
            {
                return this.PurposeCodeField;
            }
            set
            {
                this.PurposeCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkUpdateNrtClassificationRequest", Namespace="http://training.gov.au/services/")]
    public partial class BulkUpdateNrtClassificationRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime EffectiveDateField;
        
        private training.gov.au.services.BulkUpdateNrtClassificationItem[] UpdatesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public training.gov.au.services.BulkUpdateNrtClassificationItem[] Updates
        {
            get
            {
                return this.UpdatesField;
            }
            set
            {
                this.UpdatesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkUpdateNrtClassificationItem", Namespace="http://training.gov.au/services/")]
    public partial class BulkUpdateNrtClassificationItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClassificationPurposeField;
        
        private string ClassificationSchemeField;
        
        private string ClassificationValueField;
        
        private System.DateTime EffectiveDateField;
        
        private string NrtCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClassificationPurpose
        {
            get
            {
                return this.ClassificationPurposeField;
            }
            set
            {
                this.ClassificationPurposeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClassificationScheme
        {
            get
            {
                return this.ClassificationSchemeField;
            }
            set
            {
                this.ClassificationSchemeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClassificationValue
        {
            get
            {
                return this.ClassificationValueField;
            }
            set
            {
                this.ClassificationValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NrtCode
        {
            get
            {
                return this.NrtCodeField;
            }
            set
            {
                this.NrtCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkOperationTicket", Namespace="http://training.gov.au/services/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(training.gov.au.services.BulkOperationStatus))]
    public partial class BulkOperationTicket : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid OperationIdField;
        
        private System.DateTime RequestReceivedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid OperationId
        {
            get
            {
                return this.OperationIdField;
            }
            set
            {
                this.OperationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime RequestReceived
        {
            get
            {
                return this.RequestReceivedField;
            }
            set
            {
                this.RequestReceivedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkOperationStatus", Namespace="http://training.gov.au/services/")]
    public partial class BulkOperationStatus : training.gov.au.services.BulkOperationTicket
    {
        
        private string IssuerField;
        
        private int ItemCountField;
        
        private int ItemErrorCountField;
        
        private training.gov.au.services.BulkOperationItemStatus[] ItemsField;
        
        private string OperationTypeField;
        
        private System.DateTime RequestCompletedField;
        
        private string StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issuer
        {
            get
            {
                return this.IssuerField;
            }
            set
            {
                this.IssuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemCount
        {
            get
            {
                return this.ItemCountField;
            }
            set
            {
                this.ItemCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemErrorCount
        {
            get
            {
                return this.ItemErrorCountField;
            }
            set
            {
                this.ItemErrorCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public training.gov.au.services.BulkOperationItemStatus[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OperationType
        {
            get
            {
                return this.OperationTypeField;
            }
            set
            {
                this.OperationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime RequestCompleted
        {
            get
            {
                return this.RequestCompletedField;
            }
            set
            {
                this.RequestCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkOperationItemStatus", Namespace="http://training.gov.au/services/")]
    public partial class BulkOperationItemStatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime BulkOperationItemCreatedField;
        
        private System.DateTime BulkOperationItemUpdatedField;
        
        private string BulkOperationItemStatusMemberField;
        
        private string ErrorMessageField;
        
        private string DescriptionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime BulkOperationItemCreated
        {
            get
            {
                return this.BulkOperationItemCreatedField;
            }
            set
            {
                this.BulkOperationItemCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime BulkOperationItemUpdated
        {
            get
            {
                return this.BulkOperationItemUpdatedField;
            }
            set
            {
                this.BulkOperationItemUpdatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="BulkOperationItemStatus", Order=2)]
        public string BulkOperationItemStatusMember
        {
            get
            {
                return this.BulkOperationItemStatusMemberField;
            }
            set
            {
                this.BulkOperationItemStatusMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkOperationStatusQueryRequest", Namespace="http://training.gov.au/services/")]
    public partial class BulkOperationStatusQueryRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid OperationIdField;
        
        private training.gov.au.services.BulkOperationStatusQueryOption StatusQueryOptionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid OperationId
        {
            get
            {
                return this.OperationIdField;
            }
            set
            {
                this.OperationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public training.gov.au.services.BulkOperationStatusQueryOption StatusQueryOption
        {
            get
            {
                return this.StatusQueryOptionField;
            }
            set
            {
                this.StatusQueryOptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkOperationStatusQueryOption", Namespace="http://training.gov.au/services/")]
    public enum BulkOperationStatusQueryOption : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnOperationStatus = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnOperationItemCount = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnOperationItemErrorCount = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnOperationItemDetails = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnAll = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnDefault = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkOperationStatusRequest", Namespace="http://training.gov.au/services/")]
    public partial class BulkOperationStatusRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTimeOffset> EndDateField;
        
        private string IssuerField;
        
        private System.DateTimeOffset StartDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTimeOffset> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issuer
        {
            get
            {
                return this.IssuerField;
            }
            set
            {
                this.IssuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTimeOffset StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://training.gov.au/services/")]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private training.gov.au.services.ValidationError[] ErrorsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public training.gov.au.services.ValidationError[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationError", Namespace="http://training.gov.au/services/")]
    public partial class ValidationError : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string MessageField;
        
        private training.gov.au.services.ValidationErrorSeverity SeverityField;
        
        private string SubCodeField;
        
        private string ValidationTargetField;
        
        private string ContextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public training.gov.au.services.ValidationErrorSeverity Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                this.SeverityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCode
        {
            get
            {
                return this.SubCodeField;
            }
            set
            {
                this.SubCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationTarget
        {
            get
            {
                return this.ValidationTargetField;
            }
            set
            {
                this.ValidationTargetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Context
        {
            get
            {
                return this.ContextField;
            }
            set
            {
                this.ContextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationErrorSeverity", Namespace="http://training.gov.au/services/")]
    public enum ValidationErrorSeverity : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
}
namespace System
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeOffset", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial struct DateTimeOffset : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private short OffsetMinutesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short OffsetMinutes
        {
            get
            {
                return this.OffsetMinutesField;
            }
            set
            {
                this.OffsetMinutesField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://training.gov.au/services/", ConfigurationName="IClassificationService")]
public interface IClassificationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/GetServerTime", ReplyAction="http://training.gov.au/services/IClassificationService/GetServerTimeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/GetServerTimeValidationFau" +
        "ltFault", Name="ValidationFault")]
    System.DateTime GetServerTime();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/GetServerTime", ReplyAction="http://training.gov.au/services/IClassificationService/GetServerTimeResponse")]
    System.Threading.Tasks.Task<System.DateTime> GetServerTimeAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/SearchRtoClassificationsBy" +
        "Scheme", ReplyAction="http://training.gov.au/services/IClassificationService/SearchRtoClassificationsBy" +
        "SchemeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/SearchRtoClassificationsBy" +
        "SchemeValidationFaultFault", Name="ValidationFault")]
    training.gov.au.services.RtoClassificationSchemeResult SearchRtoClassificationsByScheme(string SchemeCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/SearchRtoClassificationsBy" +
        "Scheme", ReplyAction="http://training.gov.au/services/IClassificationService/SearchRtoClassificationsBy" +
        "SchemeResponse")]
    System.Threading.Tasks.Task<training.gov.au.services.RtoClassificationSchemeResult> SearchRtoClassificationsBySchemeAsync(string SchemeCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/SearchNrtClassificationsBy" +
        "Scheme", ReplyAction="http://training.gov.au/services/IClassificationService/SearchNrtClassificationsBy" +
        "SchemeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/SearchNrtClassificationsBy" +
        "SchemeValidationFaultFault", Name="ValidationFault")]
    training.gov.au.services.NrtClassificationSchemeResult SearchNrtClassificationsByScheme(string SchemeCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/SearchNrtClassificationsBy" +
        "Scheme", ReplyAction="http://training.gov.au/services/IClassificationService/SearchNrtClassificationsBy" +
        "SchemeResponse")]
    System.Threading.Tasks.Task<training.gov.au.services.NrtClassificationSchemeResult> SearchNrtClassificationsBySchemeAsync(string SchemeCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/AddClassificationValue", ReplyAction="http://training.gov.au/services/IClassificationService/AddClassificationValueResp" +
        "onse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/AddClassificationValueVali" +
        "dationFaultFault", Name="ValidationFault")]
    void AddClassificationValue(training.gov.au.services.ClassificationValueUpdateRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/AddClassificationValue", ReplyAction="http://training.gov.au/services/IClassificationService/AddClassificationValueResp" +
        "onse")]
    System.Threading.Tasks.Task AddClassificationValueAsync(training.gov.au.services.ClassificationValueUpdateRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/AddRtoClassificationsSchem" +
        "e", ReplyAction="http://training.gov.au/services/IClassificationService/AddRtoClassificationsSchem" +
        "eResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/AddRtoClassificationsSchem" +
        "eValidationFaultFault", Name="ValidationFault")]
    void AddRtoClassificationsScheme(training.gov.au.services.RtoClassificationScheme request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/AddRtoClassificationsSchem" +
        "e", ReplyAction="http://training.gov.au/services/IClassificationService/AddRtoClassificationsSchem" +
        "eResponse")]
    System.Threading.Tasks.Task AddRtoClassificationsSchemeAsync(training.gov.au.services.RtoClassificationScheme request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/AddNrtClassificationsSchem" +
        "e", ReplyAction="http://training.gov.au/services/IClassificationService/AddNrtClassificationsSchem" +
        "eResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/AddNrtClassificationsSchem" +
        "eValidationFaultFault", Name="ValidationFault")]
    void AddNrtClassificationsScheme(training.gov.au.services.NrtClassificationScheme request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/AddNrtClassificationsSchem" +
        "e", ReplyAction="http://training.gov.au/services/IClassificationService/AddNrtClassificationsSchem" +
        "eResponse")]
    System.Threading.Tasks.Task AddNrtClassificationsSchemeAsync(training.gov.au.services.NrtClassificationScheme request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/UpdateRtoClassificationSch" +
        "eme", ReplyAction="http://training.gov.au/services/IClassificationService/UpdateRtoClassificationSch" +
        "emeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/UpdateRtoClassificationSch" +
        "emeValidationFaultFault", Name="ValidationFault")]
    void UpdateRtoClassificationScheme(training.gov.au.services.RtoClassificationScheme request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/UpdateRtoClassificationSch" +
        "eme", ReplyAction="http://training.gov.au/services/IClassificationService/UpdateRtoClassificationSch" +
        "emeResponse")]
    System.Threading.Tasks.Task UpdateRtoClassificationSchemeAsync(training.gov.au.services.RtoClassificationScheme request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/UpdateNrtClassificationSch" +
        "eme", ReplyAction="http://training.gov.au/services/IClassificationService/UpdateNrtClassificationSch" +
        "emeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/UpdateNrtClassificationSch" +
        "emeValidationFaultFault", Name="ValidationFault")]
    void UpdateNrtClassificationScheme(training.gov.au.services.NrtClassificationScheme request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/UpdateNrtClassificationSch" +
        "eme", ReplyAction="http://training.gov.au/services/IClassificationService/UpdateNrtClassificationSch" +
        "emeResponse")]
    System.Threading.Tasks.Task UpdateNrtClassificationSchemeAsync(training.gov.au.services.NrtClassificationScheme request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/IsClassificationSchemeInUs" +
        "e", ReplyAction="http://training.gov.au/services/IClassificationService/IsClassificationSchemeInUs" +
        "eResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/IsClassificationSchemeInUs" +
        "eValidationFaultFault", Name="ValidationFault")]
    bool IsClassificationSchemeInUse(training.gov.au.services.ClassificationGetClassificationRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/IsClassificationSchemeInUs" +
        "e", ReplyAction="http://training.gov.au/services/IClassificationService/IsClassificationSchemeInUs" +
        "eResponse")]
    System.Threading.Tasks.Task<bool> IsClassificationSchemeInUseAsync(training.gov.au.services.ClassificationGetClassificationRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/DeleteClassificationScheme" +
        "", ReplyAction="http://training.gov.au/services/IClassificationService/DeleteClassificationScheme" +
        "Response")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/DeleteClassificationScheme" +
        "ValidationFaultFault", Name="ValidationFault")]
    void DeleteClassificationScheme(training.gov.au.services.ClassificationGetClassificationRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/DeleteClassificationScheme" +
        "", ReplyAction="http://training.gov.au/services/IClassificationService/DeleteClassificationScheme" +
        "Response")]
    System.Threading.Tasks.Task DeleteClassificationSchemeAsync(training.gov.au.services.ClassificationGetClassificationRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/GetClassificationPurpose", ReplyAction="http://training.gov.au/services/IClassificationService/GetClassificationPurposeRe" +
        "sponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/GetClassificationPurposeVa" +
        "lidationFaultFault", Name="ValidationFault")]
    training.gov.au.services.ClassificationPurpose[] GetClassificationPurpose();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/GetClassificationPurpose", ReplyAction="http://training.gov.au/services/IClassificationService/GetClassificationPurposeRe" +
        "sponse")]
    System.Threading.Tasks.Task<training.gov.au.services.ClassificationPurpose[]> GetClassificationPurposeAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/IsClassificationPurposeExi" +
        "sts", ReplyAction="http://training.gov.au/services/IClassificationService/IsClassificationPurposeExi" +
        "stsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/IsClassificationPurposeExi" +
        "stsValidationFaultFault", Name="ValidationFault")]
    bool IsClassificationPurposeExists(string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/IsClassificationPurposeExi" +
        "sts", ReplyAction="http://training.gov.au/services/IClassificationService/IsClassificationPurposeExi" +
        "stsResponse")]
    System.Threading.Tasks.Task<bool> IsClassificationPurposeExistsAsync(string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/AddClassificationPurpose", ReplyAction="http://training.gov.au/services/IClassificationService/AddClassificationPurposeRe" +
        "sponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/AddClassificationPurposeVa" +
        "lidationFaultFault", Name="ValidationFault")]
    void AddClassificationPurpose(training.gov.au.services.ClassificationPurpose request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/AddClassificationPurpose", ReplyAction="http://training.gov.au/services/IClassificationService/AddClassificationPurposeRe" +
        "sponse")]
    System.Threading.Tasks.Task AddClassificationPurposeAsync(training.gov.au.services.ClassificationPurpose request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/UpdateClassificationPurpos" +
        "e", ReplyAction="http://training.gov.au/services/IClassificationService/UpdateClassificationPurpos" +
        "eResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/UpdateClassificationPurpos" +
        "eValidationFaultFault", Name="ValidationFault")]
    void UpdateClassificationPurpose(training.gov.au.services.ClassificationPurpose request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/UpdateClassificationPurpos" +
        "e", ReplyAction="http://training.gov.au/services/IClassificationService/UpdateClassificationPurpos" +
        "eResponse")]
    System.Threading.Tasks.Task UpdateClassificationPurposeAsync(training.gov.au.services.ClassificationPurpose request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/IsClassificationPurposeInU" +
        "se", ReplyAction="http://training.gov.au/services/IClassificationService/IsClassificationPurposeInU" +
        "seResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/IsClassificationPurposeInU" +
        "seValidationFaultFault", Name="ValidationFault")]
    bool IsClassificationPurposeInUse(string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/IsClassificationPurposeInU" +
        "se", ReplyAction="http://training.gov.au/services/IClassificationService/IsClassificationPurposeInU" +
        "seResponse")]
    System.Threading.Tasks.Task<bool> IsClassificationPurposeInUseAsync(string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/DeleteClassificationPurpos" +
        "e", ReplyAction="http://training.gov.au/services/IClassificationService/DeleteClassificationPurpos" +
        "eResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/DeleteClassificationPurpos" +
        "eValidationFaultFault", Name="ValidationFault")]
    void DeleteClassificationPurpose(string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/DeleteClassificationPurpos" +
        "e", ReplyAction="http://training.gov.au/services/IClassificationService/DeleteClassificationPurpos" +
        "eResponse")]
    System.Threading.Tasks.Task DeleteClassificationPurposeAsync(string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/SubmitUpdateNrtClassificat" +
        "ionRequest", ReplyAction="http://training.gov.au/services/IClassificationService/SubmitUpdateNrtClassificat" +
        "ionRequestResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/SubmitUpdateNrtClassificat" +
        "ionRequestValidationFaultFault", Name="ValidationFault")]
    training.gov.au.services.BulkOperationTicket SubmitUpdateNrtClassificationRequest(training.gov.au.services.BulkUpdateNrtClassificationRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/SubmitUpdateNrtClassificat" +
        "ionRequest", ReplyAction="http://training.gov.au/services/IClassificationService/SubmitUpdateNrtClassificat" +
        "ionRequestResponse")]
    System.Threading.Tasks.Task<training.gov.au.services.BulkOperationTicket> SubmitUpdateNrtClassificationRequestAsync(training.gov.au.services.BulkUpdateNrtClassificationRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/GetBulkOperationStatus", ReplyAction="http://training.gov.au/services/IClassificationService/GetBulkOperationStatusResp" +
        "onse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/GetBulkOperationStatusVali" +
        "dationFaultFault", Name="ValidationFault")]
    training.gov.au.services.BulkOperationStatus GetBulkOperationStatus(training.gov.au.services.BulkOperationStatusQueryRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/GetBulkOperationStatus", ReplyAction="http://training.gov.au/services/IClassificationService/GetBulkOperationStatusResp" +
        "onse")]
    System.Threading.Tasks.Task<training.gov.au.services.BulkOperationStatus> GetBulkOperationStatusAsync(training.gov.au.services.BulkOperationStatusQueryRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/GetBulkOperations", ReplyAction="http://training.gov.au/services/IClassificationService/GetBulkOperationsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(training.gov.au.services.ValidationFault), Action="http://training.gov.au/services/IClassificationService/GetBulkOperationsValidatio" +
        "nFaultFault", Name="ValidationFault")]
    training.gov.au.services.BulkOperationStatus[] GetBulkOperations(training.gov.au.services.BulkOperationStatusRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/IClassificationService/GetBulkOperations", ReplyAction="http://training.gov.au/services/IClassificationService/GetBulkOperationsResponse")]
    System.Threading.Tasks.Task<training.gov.au.services.BulkOperationStatus[]> GetBulkOperationsAsync(training.gov.au.services.BulkOperationStatusRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IClassificationServiceChannel : IClassificationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ClassificationServiceClient : System.ServiceModel.ClientBase<IClassificationService>, IClassificationService
{
    
    public ClassificationServiceClient()
    {
    }
    
    public ClassificationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ClassificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ClassificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ClassificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.DateTime GetServerTime()
    {
        return base.Channel.GetServerTime();
    }
    
    public System.Threading.Tasks.Task<System.DateTime> GetServerTimeAsync()
    {
        return base.Channel.GetServerTimeAsync();
    }
    
    public training.gov.au.services.RtoClassificationSchemeResult SearchRtoClassificationsByScheme(string SchemeCode)
    {
        return base.Channel.SearchRtoClassificationsByScheme(SchemeCode);
    }
    
    public System.Threading.Tasks.Task<training.gov.au.services.RtoClassificationSchemeResult> SearchRtoClassificationsBySchemeAsync(string SchemeCode)
    {
        return base.Channel.SearchRtoClassificationsBySchemeAsync(SchemeCode);
    }
    
    public training.gov.au.services.NrtClassificationSchemeResult SearchNrtClassificationsByScheme(string SchemeCode)
    {
        return base.Channel.SearchNrtClassificationsByScheme(SchemeCode);
    }
    
    public System.Threading.Tasks.Task<training.gov.au.services.NrtClassificationSchemeResult> SearchNrtClassificationsBySchemeAsync(string SchemeCode)
    {
        return base.Channel.SearchNrtClassificationsBySchemeAsync(SchemeCode);
    }
    
    public void AddClassificationValue(training.gov.au.services.ClassificationValueUpdateRequest request)
    {
        base.Channel.AddClassificationValue(request);
    }
    
    public System.Threading.Tasks.Task AddClassificationValueAsync(training.gov.au.services.ClassificationValueUpdateRequest request)
    {
        return base.Channel.AddClassificationValueAsync(request);
    }
    
    public void AddRtoClassificationsScheme(training.gov.au.services.RtoClassificationScheme request)
    {
        base.Channel.AddRtoClassificationsScheme(request);
    }
    
    public System.Threading.Tasks.Task AddRtoClassificationsSchemeAsync(training.gov.au.services.RtoClassificationScheme request)
    {
        return base.Channel.AddRtoClassificationsSchemeAsync(request);
    }
    
    public void AddNrtClassificationsScheme(training.gov.au.services.NrtClassificationScheme request)
    {
        base.Channel.AddNrtClassificationsScheme(request);
    }
    
    public System.Threading.Tasks.Task AddNrtClassificationsSchemeAsync(training.gov.au.services.NrtClassificationScheme request)
    {
        return base.Channel.AddNrtClassificationsSchemeAsync(request);
    }
    
    public void UpdateRtoClassificationScheme(training.gov.au.services.RtoClassificationScheme request)
    {
        base.Channel.UpdateRtoClassificationScheme(request);
    }
    
    public System.Threading.Tasks.Task UpdateRtoClassificationSchemeAsync(training.gov.au.services.RtoClassificationScheme request)
    {
        return base.Channel.UpdateRtoClassificationSchemeAsync(request);
    }
    
    public void UpdateNrtClassificationScheme(training.gov.au.services.NrtClassificationScheme request)
    {
        base.Channel.UpdateNrtClassificationScheme(request);
    }
    
    public System.Threading.Tasks.Task UpdateNrtClassificationSchemeAsync(training.gov.au.services.NrtClassificationScheme request)
    {
        return base.Channel.UpdateNrtClassificationSchemeAsync(request);
    }
    
    public bool IsClassificationSchemeInUse(training.gov.au.services.ClassificationGetClassificationRequest request)
    {
        return base.Channel.IsClassificationSchemeInUse(request);
    }
    
    public System.Threading.Tasks.Task<bool> IsClassificationSchemeInUseAsync(training.gov.au.services.ClassificationGetClassificationRequest request)
    {
        return base.Channel.IsClassificationSchemeInUseAsync(request);
    }
    
    public void DeleteClassificationScheme(training.gov.au.services.ClassificationGetClassificationRequest request)
    {
        base.Channel.DeleteClassificationScheme(request);
    }
    
    public System.Threading.Tasks.Task DeleteClassificationSchemeAsync(training.gov.au.services.ClassificationGetClassificationRequest request)
    {
        return base.Channel.DeleteClassificationSchemeAsync(request);
    }
    
    public training.gov.au.services.ClassificationPurpose[] GetClassificationPurpose()
    {
        return base.Channel.GetClassificationPurpose();
    }
    
    public System.Threading.Tasks.Task<training.gov.au.services.ClassificationPurpose[]> GetClassificationPurposeAsync()
    {
        return base.Channel.GetClassificationPurposeAsync();
    }
    
    public bool IsClassificationPurposeExists(string code)
    {
        return base.Channel.IsClassificationPurposeExists(code);
    }
    
    public System.Threading.Tasks.Task<bool> IsClassificationPurposeExistsAsync(string code)
    {
        return base.Channel.IsClassificationPurposeExistsAsync(code);
    }
    
    public void AddClassificationPurpose(training.gov.au.services.ClassificationPurpose request)
    {
        base.Channel.AddClassificationPurpose(request);
    }
    
    public System.Threading.Tasks.Task AddClassificationPurposeAsync(training.gov.au.services.ClassificationPurpose request)
    {
        return base.Channel.AddClassificationPurposeAsync(request);
    }
    
    public void UpdateClassificationPurpose(training.gov.au.services.ClassificationPurpose request)
    {
        base.Channel.UpdateClassificationPurpose(request);
    }
    
    public System.Threading.Tasks.Task UpdateClassificationPurposeAsync(training.gov.au.services.ClassificationPurpose request)
    {
        return base.Channel.UpdateClassificationPurposeAsync(request);
    }
    
    public bool IsClassificationPurposeInUse(string code)
    {
        return base.Channel.IsClassificationPurposeInUse(code);
    }
    
    public System.Threading.Tasks.Task<bool> IsClassificationPurposeInUseAsync(string code)
    {
        return base.Channel.IsClassificationPurposeInUseAsync(code);
    }
    
    public void DeleteClassificationPurpose(string code)
    {
        base.Channel.DeleteClassificationPurpose(code);
    }
    
    public System.Threading.Tasks.Task DeleteClassificationPurposeAsync(string code)
    {
        return base.Channel.DeleteClassificationPurposeAsync(code);
    }
    
    public training.gov.au.services.BulkOperationTicket SubmitUpdateNrtClassificationRequest(training.gov.au.services.BulkUpdateNrtClassificationRequest request)
    {
        return base.Channel.SubmitUpdateNrtClassificationRequest(request);
    }
    
    public System.Threading.Tasks.Task<training.gov.au.services.BulkOperationTicket> SubmitUpdateNrtClassificationRequestAsync(training.gov.au.services.BulkUpdateNrtClassificationRequest request)
    {
        return base.Channel.SubmitUpdateNrtClassificationRequestAsync(request);
    }
    
    public training.gov.au.services.BulkOperationStatus GetBulkOperationStatus(training.gov.au.services.BulkOperationStatusQueryRequest request)
    {
        return base.Channel.GetBulkOperationStatus(request);
    }
    
    public System.Threading.Tasks.Task<training.gov.au.services.BulkOperationStatus> GetBulkOperationStatusAsync(training.gov.au.services.BulkOperationStatusQueryRequest request)
    {
        return base.Channel.GetBulkOperationStatusAsync(request);
    }
    
    public training.gov.au.services.BulkOperationStatus[] GetBulkOperations(training.gov.au.services.BulkOperationStatusRequest request)
    {
        return base.Channel.GetBulkOperations(request);
    }
    
    public System.Threading.Tasks.Task<training.gov.au.services.BulkOperationStatus[]> GetBulkOperationsAsync(training.gov.au.services.BulkOperationStatusRequest request)
    {
        return base.Channel.GetBulkOperationsAsync(request);
    }
}
